### ISSUE TITLE
Error when installing Fuzi with SPM

### ISSUE THREAD

**Issue by 1105420698** [cezheng/Fuzi#108]
### Description:
* Expected behaviour:
Fuzi to be successfully installed.
* Actual behaviour:
Installation error: `the build setting 'headerSearchPath' contains invalid component(s): $(SDKROOT)`

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [ ] CocoaPods, version:
	- [x] SPM
	- [ ] Manually

* Fuzi version: Latest
* Xcode version: 11.3.1

### How to reproduce:
Install Fuzi by following the README

**Comment by ernesto-elsaesser** [comment]
Hi 1105420698,

there is already a fix on the `master` branch that allows proper installation with Xcode 11.4: https://github.com/cezheng/Fuzi/commit/64afdf8003f8e1b730868b6f5453a6a7149aff9e

I just installed Xcode 11.4 (GM released yesterday) and created a dependency on Fuzi using branch `master` instead of a version tag. This worked for me.

Now the developers only have to release the fix! 🙂

**Comment by cezheng** [comment]
Sorry about forgetting to draft a release. I'll do that right now.
