### ISSUE TITLE
Can't import Fuzi into new project

### ISSUE THREAD

**Issue by minhthuc251** [cezheng/Fuzi#4]
This is error when i import Fuzi into my project by cocoapods version -0.39.0 (/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods.rb)
<img width="904" alt="screen shot 2015-11-24 at 4 12 51 pm" src="https://cloud.githubusercontent.com/assets/5000594/11362488/7614fb2a-92c6-11e5-9535-c1080f5345ab.png">
<img width="571" alt="screen shot 2015-11-24 at 4 12 19 pm" src="https://cloud.githubusercontent.com/assets/5000594/11362502/97416efa-92c6-11e5-878c-4e61d282b7cd.png">
This is step when i install success Fuzi . 
My xcode version is 7.1.1
<img width="264" alt="screen shot 2015-11-24 at 4 16 14 pm" src="https://cloud.githubusercontent.com/assets/5000594/11362527/bb1b01ce-92c6-11e5-886a-8ab2a3615885.png">

**Comment by cezheng** [comment]
@minhthuc251 

Hi, you should use the `TestFuzi.xcworkspace` generated by CocoaPods rather than the original TestFuzi.xcodeproj. CocoaPods puts all dependencies in another project and you need to use the workspace to find the dependencies.

As suggested in your screenshot, CocoaPods has told you to use that xcworkspace

**Comment by minhthuc251** [comment]
Thank you very much @cezheng
