### ISSUE TITLE
Parsing invalid document will crash

### ISSUE THREAD

**Issue by ened** [cezheng/Fuzi#40]
When creating a XMLDocument instance like this:

``` swift
guard let XML = try? XMLDocument(data: validData) else {
    return .failure(DataRequest.createSerializerFailure("Invalid XML"))
}
```
alternatively:
``` swift
guard let XML = try? XMLDocument(string: String(data: validData, encoding: .utf8)!) else {
    return .failure(DataRequest.createSerializerFailure("Invalid XML"))
}
```

Then I would expect the .failure block to be run. Instead, I get `fatal error: unexpectedly found nil while unwrapping an Optional value` in `XMLDocument.init`:
![screen shot 2016-10-26 at 13 01 24](https://cloud.githubusercontent.com/assets/269860/19712878/55c96ad0-9b7c-11e6-8f73-90fda88625dc.png)

`validData` contains the UTF8 string "RES" (just some garbage, really).

This _used_ to work, but now crashes. Is that related to Swift3?

**Comment by ened** [comment]
Empty string works, though:

``` swift
guard let XML = try? XMLDocument(string: "") else {
    return .failure(DataRequest.createSerializerFailure("Invalid XML"))
}
```

**Comment by cezheng** [comment]
Thanks for reporting.

Yes it is caused by the UnsafePointer change in Swift 3 where it changed some libxml2 functions to return implicitly unwrapped optionals. I have fixed this in [this commit](https://github.com/cezheng/Fuzi/commit/6e19557facfb70fb29f12404ef2de477b18a6e9b). Will draft a patch release after tests passed.

**Comment by cezheng** [comment]
Please use release [1.0.1](https://github.com/cezheng/Fuzi/releases/tag/1.0.1).
