### ISSUE TITLE
Unsupported Architecturesuploading to app store

### ISSUE THREAD

**Issue by ekampf** [cezheng/Fuzi#41]
I've integrated Fuzi using carthage as said in the README.
Code works great when I ran in simulator.
Howevere, Im getting the following error trying to upload to appstore:
```
ERROR ITMS-90087: "Unsupported Architectures. The executable for StockWatch.app/Frameworks/Fuzi.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'StockWatch.app/Frameworks/Fuzi.framework/Fuzi' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
```

Any idea?

**Comment by cezheng** [comment]
Carthage is also compiling the framework for simulators, if you just copy that framework into you app bundle it will also contain binaries for simulator. So you will need to add a script build phase for removing those parts, as stated in the Carthage repo's [README](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos)

I'm closing this since it is just a Carthage issue.
