### ISSUE TITLE
parseHTML Some questions

### ISSUE THREAD

**Issue by LazyScream** [cezheng/Fuzi#42]
Here's my code
```
func parseHTML () {
        
        let html = "http://ec2-52-193-39-25.ap-northeast-1.compute.amazonaws.com/ForMyDear/"
        do {
        let doc = try HTMLDocument(string: html, encoding: String.Encoding.utf8)
        
        print(doc.title) // gets <title>'s innerHTML in <head>
        print(doc.head)  // gets <head> element
        print(doc.body)
        }
        catch let error {
            print(error)
        }
    }
```

the print(doc.title) There was a yellow exclamation point
Expression implicitly coerced from 'XMLElement?' To Any

Where is the problem?
I'm sorry. I'm a new Swift

**Comment by cezheng** [comment]
@LazyScream Hi, I guess this is a new compiler warning when you try to print something that is optional. In Xcode 8.1 there is a recommended auto correction of your code, by adding a default value in case the value is nil. Just click on the yellow exclamation symbol on the left then press enter, then type the default value.

Since this is not a issue related to the framework, I will just close it.

**Comment by LazyScream** [comment]
thx all
