### ISSUE TITLE
Find youtube video code - question

### ISSUE THREAD

**Issue by NBibikov** [cezheng/Fuzi#62]
### Description:
* Expected behaviour: question

* Actual behaviour: question

### Environment
* Package Manager:
	- [ ] Carthage, version:
	- [x] CocoaPods, version: latest
	- [ ] Manually

* Fuzi version: latest
* Xcode version: latest

### How to reproduce:
Hello! Thanks for library.  I have some code in my html. All of them inside brackets - []. How i can catch them and take code for video?

> [vc_video link=’https://youtu.be/xxxxxxxxxxx’]

**Comment by cezheng** [comment]
Youtube videos url is embedded in one of the <script> elements of the page source, so using Fuzi won't help with that. You can use regex for that. I did some similar thing a few years ago, the code is in C++ but the logic shall be the same if you write it in Swift. I won't guarantee that it will work now since the youtube website might have changed during the time.

https://github.com/cezheng/Tu/blob/play/Tu/XPFService/Utils/VideoUtil.cpp#L8

Also, this is not a Fuzi issue so I'm closing it.
