### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by tosbaha** [cezheng/Fuzi#7]
I am trying to use Fuzi on Linux and therefore SPM is the way to go. Could you add support for SPM ? Thanks

**Comment by cezheng** [comment]
Hi @tosbaha 
I have thought about  supporting Linux when Swift went open source a month ago. But after having a check on the current status of https://github.com/apple/swift-corelibs-foundation , I realized that Fuzi cannot work on Linux at the moment due the lack of implementations of many Foundation methods.

But thinking about removing foundation dependencies on Fuzi, some APIs such as https://github.com/cezheng/Fuzi/blob/master/Fuzi/Document.swift#L34 , seems hard to deal with.

I definitely want to support Linux as soon as possible, but I haven't come up with a good way yet. Do you have any suggestions?

**Comment by cezheng** [comment]
Also, I haven't figured out the right way to include the libxml2 module yet

**Comment by tosbaha** [comment]
I have tried following,

Clibxml2 Directory
===

**Package.swift**


```swift
import PackageDescription

let package = Package(
    name: "Clibxml2"
)
```

**module.map**

```
module Clibxml2 [system] {
  header "/usr/include/libxml2/libxml/xmlreader.h"
  header "/usr/include/libxml2/libxml/xpath.h"
  header "/usr/include/libxml2/libxml/parser.h"
  header "/usr/include/libxml2/libxml/tree.h"
  header "/usr/include/libxml2/libxml/encoding.h"
  header "/usr/include/libxml2/libxml/xmlwriter.h"
  link "xml2"
  export *
}
```
Fuzi Directory
==
**Package.swift**
```swift
import PackageDescription

let package = Package(
    name: "Fuzi",
    dependencies: [
        .Package(url: "../Clibxml2", Version(1,0,0))]
)
```
**Sources**
Document.swift
Error.swift
NodeSet.swift
Queryable.swift
Element.swift
Helpers.swift
Node.swift

Edited Helper.swift file to change import libxml2 to import Clibxml2


It complains about file path errors. 

I also tried to use https://github.com/aktowns/CXML2/ as Package and changed import libxml2 to CXML2 but again it failed with some file errors. I really don't get SPM, when I do some changes to source files, it doesn't pick up. I had to re-init the git and build it again. Anyway, I hope you can figure it out since I couldn't figure it out for couple of hours.

**Comment by cezheng** [comment]
I will be looking at this issue. SPM does not well support mudulemaps yet
https://bugs.swift.org/browse/SR-145

**Comment by cezheng** [comment]
I somehow resolved the path issues of libxml2, but sadly the swift-corelibs-foundation is hopelessly broken at the moment, while CFString, NSString being almost unusable and NSRegularExpression being completely empty, along with a lot of syntax issue relating to the UnsafePointer<Int8> and [CChar], I don't think this can be resolved very soon. But I will take some time to deal with it when I have more free time.

**Comment by tosbaha** [comment]
Could you elaborate on how you solved the path issue? It may help me on the long run. Thanks.

**Comment by cezheng** [comment]
It's a bloody dirty trick, I symlinked /usr/include/libxml2 and /usr/include/libxml2/libxml to the same directory of the module map. I hope I won't have to do this soon

**Comment by tosbaha** [comment]
I wished there was more elegant way :( I hope SPM matures soon to fix this issues. Thanks and keep up the good work :+1:  
PS: Since Swift is open source, it is only time to get better support for Linux. Instead of libxml2, would you consider using other HTML parser such as  [gumbo](https://github.com/google/gumbo-parser)? Because libxml2 is not designed for parsing faulty HTML files. I always write some workaround code to parse faulty HTML files.

**Comment by cezheng** [comment]
The original purpose of making Fuzi is to make a lightweight & fast parser for iOS devices to easily deal with tasks such as scraping web pages & dealing with various XML files, due to the fact that NSXMLDocument is not available on iOS, NSXMLParser's API is cumbersome.

And the principle that Fuzi is suppose to take is to keep itself lightweight & its design simple. You can see that the integration size of Fuzi on Cocoapods is only 76KB as of version 0.3.0(https://cocoapods.org/pods/Fuzi), thanks to the fact that iOS provides libxml2 in its SDK.

Looking at the Objective-C gumbo parser: https://cocoapods.org/pods/ObjectiveGumbo , it takes 564KB which is way more than Fuzi.

So if I'm to use gumbo in Swift, I would prefer to have another wrapper library.

**Comment by tosbaha** [comment]
I totally understand your point. However I believe that efficiency out rules 488KB difference. I know that for most HTML pages(if they are standard HTML), libxml2 works very well. However libxml2 chokes if it sees non standard HTML with broken or missing tags. Thanks for the library

**Comment by cezheng** [comment]
Sure, I believe there would be plenty of cases where gumbo would do what libxml2 cannot. In that case I believe we would need something like `GumboSwift` or so, with a link in the official gumbo repo's readme: https://github.com/google/gumbo-parser

However, when we come to look at the stars for libxml2 wrapper & gumbo wrapper libraries, which somehow reflects the needs of the majority
### ObjC
1600+ vs 100+
#### libxml2
* https://github.com/mattt/Ono
* https://github.com/topfunky/hpple
#### gumbo
* https://github.com/programmingthomas/ObjectiveGumbo
* https://github.com/tracy-e/OCGumbo

### Ruby
3000+ vs 100-
#### libxml2
* https://github.com/sparklemotion/nokogiri
#### gumbo
* https://github.com/nevir/ruby-gumbo
* https://github.com/rubys/nokogumbo

### JavaScript
500+ vs 100+
####  libxml2
* https://github.com/polotek/libxmljs
#### gumbo
* https://github.com/karlwestin/node-gumbo-parser

Off course gumbo is young compared with libxml2 so it does not yet have time to accumulate so many users, but for most people libxml2 just suits their need and they would not be bothered to look for another parser like gumbo.

Changing a library that targets majority to satisfy the need for minority does not seem to be a very good idea to me. That's why I would prefer to have another library that targets them.

**Comment by tosbaha** [comment]
I am not trying to say that gumbo is more popular than libxml2. That would be to naive. What I am trying to say that gumbo is better HTML parser compared to libxml2. I also believe that star of projects doesn't *fully* show neither the quality or capability of the code. For example when you compare star's of Ono, hpple, Fuzi, Kanna, Ji they all differ. However the difference of starts doesn't mean that one project is superior than the other even if they use the same libxml2. Since libxml2 is not a HTML parser, in order to support CSS, all libxml2 parsers have extra layer(with regex,string search etc) to support CSS queries. As I said before, libxml2 works most of the time. That can be enough for most users.  However if you are dealing with non standard HTML pages, from different sources, you need a solid HTML parser which is tested on over 2.5 billion pages from Google's index. Instead of speaking in obscure terms, I prefer to talk in concrete example. Here is a failing test
[source.html](http://www.nacex.es/seguimientoDetalle.do?agencia_origen=4100&numero_albaran=10765875&estado=1&internacional=0&externo=N&usr=null&pas=null)
```swift
    func testTable() {
        var idx = 0

        for element in document.xpath(".//*[@id='boxContenido']//tr[6]/td/table//tr[3]/td/table//tr") {
            print(element)
            idx++
        }
        XCTAssertEqual(idx, 16, "should be exactly 16 element")
    }
```
This code works perfectly with Fuzi on iOS 9. Try to run it on iOS 8, it fails. You will scratch your head while it fails on iOS 8. You will have no choice but to use more generic ```".//*[@id='boxContenido']//tr/td/table//tr" ``` query to get all tr and skip some

**Comment by cezheng** [comment]
Yeah, guess that's a bug that lies in version of libxml2 on iOS 8

**Comment by Ajayiosdeveloper** [comment]
Nice discussion happened.Finally what you can conclude for using on Linux.I know Fuzi is good one for Apple core technologies but for supporting Linux now which is the best altaernative (only i need XML parsing with Swift 3.0) .I very need your help on this.

Thanks.

**Comment by cezheng** [comment]
I have tried adding support for it just on apple platforms, but once again, no luck. I'm so disappointed about SPM once again after 9 months.

Please see what I've found out: https://github.com/cezheng/Fuzi/issues/34#issuecomment-249348356
